language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'

sudo: false

install:
  - travis_retry composer install

script:
  - composer ci

cache:
  directories:
  - "$HOME/.composer/cache"

notifications:
  email:
    on_success: change
    on_failure: always
